[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nav2py_sicnav_controller"
version = "0.1.0"
dependencies = [
    "PyYAML>=6.0.2"
]
requires-python = ">=3.10"
description = "SICNav Controller for Navigation2 with Python integration"
readme = "README.md"
license = {text = "BSD-3-Clause"}
